version: '3.8'

volumes:
  datafiles:

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: cnabweb
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    links:
      - mysql:mysql
    ports:
      - 8082:80
    restart: always
    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      - MYSQL_DBNAME=cnabweb
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql